//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM.Authentication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuthenticationLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthenticationLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARM.Authentication.AuthenticationLocalization", typeof(AuthenticationLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string AuthenticationChangeModeButtonText {
            get {
                return ResourceManager.GetString("AuthenticationChangeModeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему произведён успешно..
        /// </summary>
        internal static string AuthenticationCompleted {
            get {
                return ResourceManager.GetString("AuthenticationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему не был произведен..
        /// </summary>
        internal static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string AuthenticationFinishButtonText {
            get {
                return ResourceManager.GetString("AuthenticationFinishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в АРМ &quot;Лингвист&quot;.
        /// </summary>
        internal static string AuthenticationHeadlineText {
            get {
                return ResourceManager.GetString("AuthenticationHeadlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу войти.
        /// </summary>
        internal static string AuthenticationHelpButtonText {
            get {
                return ResourceManager.GetString("AuthenticationHelpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь в аутентификации.
        /// </summary>
        internal static string AuthenticationHelpCaption {
            get {
                return ResourceManager.GetString("AuthenticationHelpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для аутентификации введите ваши логин и пароль..
        /// </summary>
        internal static string AuthenticationHelpMessage1 {
            get {
                return ResourceManager.GetString("AuthenticationHelpMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помните, что при вводе логина/пароля учитывается раскладка и регистр..
        /// </summary>
        internal static string AuthenticationHelpMessage2 {
            get {
                return ResourceManager.GetString("AuthenticationHelpMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы забыли ваш логин и/или пароль, то это ваши проблемы..
        /// </summary>
        internal static string AuthenticationHelpMessage3 {
            get {
                return ResourceManager.GetString("AuthenticationHelpMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введённый логин отсутствует в системе..
        /// </summary>
        internal static string AuthenticationLoginError {
            get {
                return ResourceManager.GetString("AuthenticationLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введён неверный пароль..
        /// </summary>
        internal static string AuthenticationPasswordError {
            get {
                return ResourceManager.GetString("AuthenticationPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ещё нет аккаунта?.
        /// </summary>
        internal static string AuthenticationQuestionLabelText {
            get {
                return ResourceManager.GetString("AuthenticationQuestionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гость.
        /// </summary>
        internal static string GuestLogin {
            get {
                return ResourceManager.GetString("GuestLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Был произведён гостевой вход, поэтому будет доступна лишь возможность просмотра данных..
        /// </summary>
        internal static string GuestMessage {
            get {
                return ResourceManager.GetString("GuestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алярм!.
        /// </summary>
        internal static string GuestMessageHeader {
            get {
                return ResourceManager.GetString("GuestMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин:.
        /// </summary>
        internal static string LoginLabelText {
            get {
                return ResourceManager.GetString("LoginLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        internal static string PasswordLabelText {
            get {
                return ResourceManager.GetString("PasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string RegistrationChangeModeButtonText {
            get {
                return ResourceManager.GetString("RegistrationChangeModeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация произведена успешно..
        /// </summary>
        internal static string RegistrationCompleted {
            get {
                return ResourceManager.GetString("RegistrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        internal static string RegistrationFinishButtonText {
            get {
                return ResourceManager.GetString("RegistrationFinishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация в АРМ &quot;Лингвист&quot;.
        /// </summary>
        internal static string RegistrationHeadlineText {
            get {
                return ResourceManager.GetString("RegistrationHeadlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу зарегистрироваться.
        /// </summary>
        internal static string RegistrationHelpButtonText {
            get {
                return ResourceManager.GetString("RegistrationHelpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь в регистрации.
        /// </summary>
        internal static string RegistrationHelpCaption {
            get {
                return ResourceManager.GetString("RegistrationHelpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правило регистрации только одно: выбранный вами логин должен отличаться от уже используемых в системе..
        /// </summary>
        internal static string RegistrationHelpMessage {
            get {
                return ResourceManager.GetString("RegistrationHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введённый вами логин уже используется в системе..
        /// </summary>
        internal static string RegistrationLoginExistsError {
            get {
                return ResourceManager.GetString("RegistrationLoginExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже есть аккаунт?.
        /// </summary>
        internal static string RegistrationQuestionLabelText {
            get {
                return ResourceManager.GetString("RegistrationQuestionLabelText", resourceCulture);
            }
        }
    }
}
